# Generated by Django 4.2.6 on 2023-10-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartPotApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='hummidity',
            new_name='humidity',
        ),
    ]
