# Generated by Django 4.2.6 on 2023-10-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartPotApp', '0002_rename_hummidity_history_humidity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='humidity',
        ),
    ]
