# Generated by Django 4.2.6 on 2023-12-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartPotApp', '0004_history_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='light',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='temperature',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
