# Generated by Django 4.2.6 on 2023-12-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartPotApp', '0005_alter_history_light_alter_history_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='light',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
